fix: Node 22.12 error with `dist/cjs` imports
JeremyRH/storybook-addon-code-editor pull request #54
Opened 2024-12-12 17:54 UTC by lyleaigbedion

Resolves: #53

2024-12-12 18:52 UTC, JeremyRH approved these changes
Awesome! Thank you!

2024-12-12 19:00 UTC, JeremyRH requested changes
I just realized your commits don't follow conventional commits. That is needed for automatic version bumps.
https://github.com/JeremyRH/storybook-addon-code-editor?tab=readme-ov-file#commits

2024-12-13 16:51 UTC, lyleaigbedion commented
oops. I'll file a new PR

2024-12-13 17:36 UTC, JeremyRH approved these changes

2024-12-13 19:20 UTC, merged